config/routes.rb
Rails.application.routes.draw do
   resources :contacts do
       resources :logs
   end

end

app/models/contact.rb
class Contact < ActiveRecord::Base
    before_save :full_name, :emailDown
    validates :First_Name, :Last_Name, :Email, :Title, presence: true
    has_many :logs, dependent: :destroy
    
    private
        def full_name
            self.Full_Name=self.First_Name + " " + self.Last_Name
            
        end
        
        def emailDown
            self.Email=self.Email.downcase
        end
end

app/models/log.rb
class Log < ActiveRecord::Base
  belongs_to :contact
  validates :responsible, :comment, presence: true
  default_scope -> {order(created_at: :desc)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)
  

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:Title, :First_Name, :Last_Name, :Email, :Organization, :Position)
    end
    
    
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :set_log, only: [:show, :edit, :update, :destroy]

 

  # GET /contacts/:id/logs/1
  # GET /contacts/:id/logs/1.json
  def show
  end

  # GET /contacts/:id/logs/new
  def new
    @contact = Contact.find(params[:contact_id])
    @log =@contact.logs.build
  end

  # GET /logs/1/edit
  def edit
  end

  # POST /contacts/:id/logs
  # POST /contacts/:id/logs.json
  def create
    @contact = Contact.find(params[:contact_id])
    @log = @contact.logs.build(log_params)

    respond_to do |format|
      if @log.save
        format.html { redirect_to @contact, notice: 'Log was successfully created.' }
        format.json { render :show, status: :created, location: @log }
      else
        format.html { render :new }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/:id/logs/1
  # PATCH/PUT /contacts/:id/logs/1.json
  def update
    respond_to do |format|
      if @log.update(log_params)
        format.html { redirect_to @contact, notice: 'Log was successfully updated.' }
        format.json { render :show, status: :ok, location: @log }
      else
        format.html { render :edit }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/:id/logs/1
  # DELETE /contacts/:id/logs/1.json
  def destroy
    @log.destroy
    respond_to do |format|
      format.html { redirect_to logs_url, notice: 'Log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_log
      @contact = Contact.find(params[:contact_id])
      @log = @contact.logs.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def log_params
      params.require(:log).permit(:responsible, :comment)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
    <% if @contact.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>
  
        <ul>
        <% @contact.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
       
        <p>
          <%= f.label :First_Name %><br>
          <%= f.text_field :First_Name, :required => true %>
        </p>
       
        <p>
          <%= f.label :Last_Name %><br>
          <%= f.text_field :Last_Name, :required => true %>
        </p>
         <p>
          <%= f.label :Title %><br>
          <%= f.select :Title, [['Mr', 'Mr'], ['Ms', 'Ms'], ['Dr', 'Dr'], ['Prof', 'Prof']], {prompt: 'Select Person'}, :required => true  %>
             
            
        </p>
        <p>
          <%= f.label :Email %><br>
          <%= f.email_field :Email, :required => true %>
        </p>
        <p>
          <%= f.label :Organization %><br>
          <%= f.text_field :Organization %>
        </p>
         <p>
          <%= f.label :Position %><br>
          <%= f.text_field :Position %>
        </p>
        <div class="actions">
          <%= f.submit %>
        </div>
  <% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Contacts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.Full_Name %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>First_Title: <%= @contact.Title %></p>
<p>First_Name: <%= @contact.First_Name %></p>
<p>Last_Name: <%= @contact.Last_Name %></p>
<p>Full_Name: <%= @contact.Full_Name %></p>
<p>Organization: <%= @contact.Organization %></p>
<p>Position: <%= @contact.Position %></p>
<p>Email: <%= @contact.Email %></p>




<%= render "logs/log", :collection => @contact.logs%>

<%= link_to 'New Log', new_contact_log_path(@contact) %> 
<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/logs/_log.html.erb
<%= form_for [@contact, @contact.logs.build] do |f| %>
  <p><%= f.label :comment %><br>
      <%= f.text_field :comment, :required => true %>
  </p>
  <p><%= f.label :responsible %><br>
      <%= f.text_field :responsible, :required => true %>
  </p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<% @contact.logs.each do |log| %>
 <% if log.persisted? %>

      <%= form_for [@contact, log], :method => :put  do |f| %>
        <p> <%= f.label :comment %><br>
            <%= f.text_field :comment, :required => true %>
        </p>
        <p><%= f.label :responsible %><br>
            <%= f.text_field :responsible, :required => true %>
        </p>
        <p>

        <div class="actions">
          <%= f.submit %>
        </div>
    <% end %>
  <% end %>  
<% end%>

app/views/logs/edit.html.erb
<h1>Editing Log</h1>

<%= render 'form' %>

<%= link_to 'Show', @log %> |
<%= link_to 'Back', logs_path %>

app/views/logs/new.html.erb
<h1>New Log</h1>

<%= render 'form' %>

<%= link_to 'Back', logs_path %>

app/views/logs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_contact_log_path(@contact) %>
<%= link_to 'Back', logs_path %>